#:schema node_modules/wrangler/config-schema.json
name = "lonkis2"
main = "dist/index.html"
compatibility_date = "2026-03-22"

[build]
command = "npm install --legacy-peer-deps --force && npm run build"
watch_paths = ["src/**/*.ts", "src/**/*.tsx"]
cwd = "."
amd = true

[build.upload]
format = "service-worker"

[build.upload.rules]
type = "CompiledContentType"
fallthrough = true

[env.production]
vars = { ENVIRONMENT = "production" }
