import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from 'motion/react';
import { ArrowRight } from 'lucide-react';
import { Link } from 'react-router-dom';
import { siteConfig } from '../../siteConfig';
export const Differentials = () => {
    const { badge, title, titleAccent, description, ctaText, items } = siteConfig.home.differentials;
    return (_jsx("section", { id: "differentials", className: "py-32 px-6 bg-white overflow-hidden", children: _jsx("div", { className: "max-w-7xl mx-auto", children: _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-12 gap-20 items-center", children: [_jsxs(motion.div, { initial: { opacity: 0, x: -30 }, whileInView: { opacity: 1, x: 0 }, viewport: { once: true }, className: "lg:col-span-5 space-y-8", children: [_jsxs("div", { className: "space-y-4", children: [_jsx("span", { className: "text-[10px] uppercase tracking-[0.4em] text-black/40 font-black block", children: badge }), _jsxs("h2", { className: "font-display text-4xl sm:text-5xl md:text-7xl font-black uppercase tracking-tighter leading-[0.9] text-black", children: [title, " ", _jsx("br", {}), _jsx("span", { className: "text-black/20", children: titleAccent })] })] }), _jsx("p", { className: "text-gray-500 text-base sm:text-lg font-medium leading-relaxed max-w-md", children: description }), _jsx("div", { className: "pt-4", children: _jsxs(Link, { to: "/sobre", className: "inline-flex items-center gap-4 text-[10px] uppercase tracking-[0.3em] text-black font-black group", children: [ctaText, _jsx(ArrowRight, { className: "w-4 h-4 group-hover:translate-x-2 transition-transform" })] }) })] }), _jsx("div", { className: "lg:col-span-7 grid grid-cols-1 sm:grid-cols-2 gap-6", children: items.map((item, index) => {
                            const Icon = item.icon;
                            return (_jsxs(motion.div, { initial: { opacity: 0, y: 20 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, transition: { delay: index * 0.1 }, className: "group p-8 sm:p-10 bg-zinc-50 border border-zinc-100 hover:border-black hover:bg-white transition-all duration-700 rounded-[2.5rem] sm:rounded-[3rem] relative overflow-hidden shadow-sm hover:shadow-2xl", children: [_jsx("div", { className: "absolute top-0 right-0 w-32 h-32 bg-black/5 blur-3xl rounded-full -mr-16 -mt-16 group-hover:bg-black/10 transition-colors" }), _jsx("div", { className: "w-14 h-14 sm:w-16 sm:h-16 bg-white rounded-2xl flex items-center justify-center shadow-sm group-hover:bg-black group-hover:text-white transition-all duration-500 group-hover:scale-110 group-hover:rotate-3 mb-6 sm:mb-8 relative z-10", children: _jsx(Icon, { className: "w-6 h-6 sm:w-8 sm:h-8 text-black group-hover:text-white transition-colors" }) }), _jsxs("div", { className: "relative z-10 space-y-2 sm:space-y-3", children: [_jsx("h3", { className: "font-display text-xl sm:text-2xl font-black uppercase text-black tracking-tight leading-tight", children: item.title }), _jsx("p", { className: "text-gray-400 text-xs sm:text-sm leading-relaxed font-medium group-hover:text-gray-600 transition-colors", children: item.description })] })] }, item.title));
                        }) })] }) }) }));
};
