import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion, AnimatePresence } from 'motion/react';
import * as Icons from 'lucide-react';
import { useState, useMemo } from 'react';
import { Button } from '../components/ui/Button';
import { QuoteModal } from '../components/ui/QuoteModal';
import { SEO } from '../components/ui/SEO';
import { siteConfig } from '../siteConfig';
export const ServicesPage = () => {
    const [selectedService, setSelectedService] = useState(null);
    const [searchTerm, setSearchTerm] = useState("");
    const [activeCategory, setActiveCategory] = useState("Todos");
    const filteredServices = useMemo(() => {
        return siteConfig.servicesPage.detailedServices.filter(service => {
            const matchesSearch = service.name.toLowerCase().includes(searchTerm.toLowerCase());
            const matchesCategory = activeCategory === "Todos" || service.category === activeCategory;
            return matchesSearch && matchesCategory;
        });
    }, [searchTerm, activeCategory]);
    return (_jsxs(motion.div, { initial: { opacity: 0 }, animate: { opacity: 1 }, exit: { opacity: 0 }, transition: { duration: 0.5 }, className: "pt-32 pb-24 px-6 bg-black min-h-screen relative overflow-hidden", children: [_jsx(SEO, { title: `Serviços | ${siteConfig.brand.name}`, description: "Conserto de tela, bateria, conectores e reparos em placa para todas as marcas de celulares." }), _jsx("div", { className: "absolute inset-0 z-0 opacity-10", children: _jsx("div", { className: "absolute top-0 left-0 w-full h-full bg-[radial-gradient(circle_at_50%_50%,rgba(255,255,255,0.1),transparent_70%)]" }) }), _jsxs("div", { className: "max-w-7xl mx-auto relative z-10", children: [_jsxs("div", { className: "mb-16", children: [_jsx(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, className: "inline-block px-4 py-1 bg-white/5 backdrop-blur-md rounded-full mb-6 border border-white/10", children: _jsx("span", { className: "text-[10px] uppercase tracking-[0.4em] text-white/40 font-bold", children: siteConfig.servicesPage.hero.badge }) }), _jsxs(motion.h1, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { delay: 0.1 }, className: "font-display text-4xl sm:text-5xl md:text-8xl font-black uppercase tracking-tighter mb-8 text-white leading-[0.85]", children: [siteConfig.servicesPage.hero.title, " ", _jsx("br", {}), _jsx("span", { className: "text-white/20", children: siteConfig.servicesPage.hero.titleAccent })] }), _jsxs("div", { className: "flex flex-col lg:flex-row gap-8 items-start lg:items-center justify-between", children: [_jsx("div", { className: "flex flex-wrap sm:flex-nowrap sm:overflow-x-auto gap-3 pb-4 sm:pb-0 w-full lg:w-auto no-scrollbar", children: siteConfig.servicesPage.categories.map((cat) => (_jsx("button", { onClick: () => setActiveCategory(cat), className: `px-5 sm:px-6 py-3 rounded-full text-[9px] sm:text-[10px] uppercase tracking-[0.2em] font-black transition-all border whitespace-nowrap ${activeCategory === cat
                                                ? "bg-white text-black border-white"
                                                : "bg-white/5 text-white/40 border-white/10 hover:border-white/30 hover:text-white"}`, children: cat }, cat))) }), _jsxs("div", { className: "relative w-full lg:w-80", children: [_jsx(Icons.Search, { className: "absolute left-6 top-1/2 -translate-y-1/2 w-4 h-4 text-white/20" }), _jsx("input", { type: "text", placeholder: "BUSCAR SERVI\u00C7O...", value: searchTerm, onChange: (e) => setSearchTerm(e.target.value), className: "w-full bg-white/5 border border-white/10 rounded-2xl py-4 pl-14 pr-6 text-white text-[9px] sm:text-[10px] uppercase tracking-widest focus:outline-none focus:border-white/40 transition-all font-black" }), searchTerm && (_jsx("button", { onClick: () => setSearchTerm(""), className: "absolute right-6 top-1/2 -translate-y-1/2 text-white/20 hover:text-white", children: _jsx(Icons.X, { className: "w-4 h-4" }) }))] })] })] }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-px bg-white/5 border border-white/5 rounded-[2rem] sm:rounded-[2.5rem] overflow-hidden shadow-2xl", children: _jsx(AnimatePresence, { mode: "popLayout", children: filteredServices.map((service, index) => {
                                const Icon = Icons[service.icon];
                                return (_jsxs(motion.div, { layout: true, initial: { opacity: 0, scale: 0.9 }, animate: { opacity: 1, scale: 1 }, exit: { opacity: 0, scale: 0.9 }, transition: { duration: 0.3 }, className: "group bg-zinc-900/40 p-8 sm:p-10 flex flex-col items-start hover:bg-white transition-all duration-700 border border-white/5 relative overflow-hidden", children: [_jsx("div", { className: "absolute top-0 right-0 p-6 sm:p-8 opacity-0 group-hover:opacity-100 transition-opacity", children: _jsx("div", { className: "w-2 h-2 rounded-full bg-black animate-pulse" }) }), _jsxs("div", { className: "flex justify-between w-full items-start mb-10 sm:mb-12", children: [_jsx("span", { className: "font-display text-5xl sm:text-6xl font-black text-white/5 group-hover:text-black/5 transition-colors", children: String(index + 1).padStart(2, '0') }), _jsx("div", { className: "p-4 sm:p-5 bg-white/5 rounded-[1.2rem] sm:rounded-[1.5rem] group-hover:bg-black group-hover:scale-110 transition-all duration-500", children: Icon && _jsx(Icon, { className: "w-6 h-6 sm:w-8 sm:h-8 text-white/40 group-hover:text-white transition-colors" }) })] }), _jsxs("div", { className: "space-y-2 mb-8 sm:mb-10", children: [_jsx("span", { className: "text-[9px] sm:text-[10px] uppercase tracking-[0.3em] text-white/30 group-hover:text-black/40 font-black block", children: service.category }), _jsx("h3", { className: "font-display text-xl sm:text-2xl font-black text-white group-hover:text-black mb-2 uppercase tracking-tight transition-colors leading-tight", children: service.name }), _jsx("p", { className: "text-white/40 group-hover:text-black/60 font-black text-base sm:text-lg tracking-tight", children: service.price })] }), _jsx(Button, { className: "mt-auto w-full py-5 bg-white/5 text-white border border-white/10 group-hover:bg-black group-hover:text-white group-hover:border-black transition-all rounded-2xl text-[9px] sm:text-[10px] font-black uppercase tracking-[0.3em]", onClick: () => setSelectedService({ title: service.name, price: service.price }), ariaLabel: `Solicitar orçamento para ${service.name}`, children: "Solicitar Or\u00E7amento" })] }, service.id));
                            }) }) }), filteredServices.length === 0 && (_jsxs(motion.div, { initial: { opacity: 0 }, animate: { opacity: 1 }, className: "py-32 text-center", children: [_jsx(Icons.Search, { className: "w-16 h-16 text-white/5 mx-auto mb-6" }), _jsx("h3", { className: "font-display text-2xl font-black text-white/20 uppercase tracking-widest", children: "Nenhum servi\u00E7o encontrado" }), _jsx("button", { onClick: () => { setSearchTerm(""); setActiveCategory("Todos"); }, className: "mt-6 text-[10px] uppercase tracking-[0.3em] text-white/40 hover:text-white font-black transition-colors", children: "Limpar Filtros" })] })), _jsxs("div", { className: "mt-32 pt-32 border-t border-white/5", children: [_jsxs(motion.div, { initial: { opacity: 0, y: 20 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, className: "mb-16", children: [_jsx("span", { className: "text-[10px] uppercase tracking-[0.4em] text-white/40 font-bold block mb-4", children: siteConfig.servicesPage.supportedDevices.badge }), _jsxs("h2", { className: "font-display text-4xl md:text-6xl font-black uppercase tracking-tighter text-white leading-none", children: [siteConfig.servicesPage.supportedDevices.title, " ", _jsx("br", {}), _jsx("span", { className: "text-white/20", children: siteConfig.servicesPage.supportedDevices.titleAccent })] })] }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8", children: siteConfig.servicesPage.supportedDevices.brands.map((item, index) => {
                                    const Icon = Icons[item.icon];
                                    return (_jsxs(motion.div, { initial: { opacity: 0, y: 20 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, transition: { delay: index * 0.1 }, className: "p-10 rounded-[2rem] bg-zinc-900/40 border border-white/5 hover:bg-white group transition-all duration-700", children: [_jsx("div", { className: "w-12 h-12 rounded-2xl bg-white/5 group-hover:bg-black flex items-center justify-center mb-8 transition-colors duration-500", children: Icon && _jsx(Icon, { className: "w-6 h-6 text-white/40 group-hover:text-white transition-colors" }) }), _jsx("h3", { className: "font-display text-2xl font-black text-white group-hover:text-black mb-6 uppercase tracking-tight transition-colors", children: item.brand }), _jsxs("ul", { className: "space-y-3", children: [item.models.map((model) => (_jsxs("li", { className: "text-white/40 group-hover:text-black/60 text-[10px] uppercase tracking-widest font-black flex items-center gap-3 transition-colors", children: [_jsx("div", { className: "w-1 h-1 rounded-full bg-white/20 group-hover:bg-black/20" }), model] }, model))), _jsx("li", { className: "text-white/20 group-hover:text-black/40 text-[10px] uppercase tracking-widest font-black pt-4 border-t border-white/5 group-hover:border-black/5 transition-colors", children: "+ Muitos outros modelos" })] })] }, item.brand));
                                }) })] })] }), selectedService && (_jsx(QuoteModal, { isOpen: !!selectedService, onClose: () => setSelectedService(null), serviceName: selectedService.title, price: selectedService.price }))] }));
};
